# Generated by Django 5.1.6 on 2025-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
